spring:
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
    redis:
      database: 0
      host: 192.168.72.128
      port: 6379
      password:
      timeout: 20000
      #cluster:
      #max-redirects:
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
    datasource:
      username: root
      password: 19921118
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
domain:
  name: www.huihuang.com


